/** Các trường có thể gửi cho LLM và gợi ý targetField mẫu quy tắc (id = path trên Lead hoặc key trong fieldExtras). */
export const AI_LEAD_FIELD_OPTIONS: { id: string; label: string; extra?: boolean }[] = [
  { id: 'customerId', label: 'Mã khách hàng (customerId)' },
  { id: 'dateOfBirth', label: 'Ngày sinh (chuỗi — dateOfBirth)' },
  { id: 'fullName', label: 'Họ tên' },
  { id: 'phone', label: 'SĐT' },
  { id: 'email', label: 'Email' },
  { id: 'parentPhone', label: 'SĐT phụ huynh' },
  { id: 'majorInterest', label: 'Ngành quan tâm' },
  { id: 'educationLevel', label: 'Hình thức học quan tâm (educationLevel)' },
  { id: 'ethnicity', label: 'Dân tộc' },
  { id: 'permanentAddress', label: 'Địa chỉ thường trú' },
  { id: 'currentResidence', label: 'Nơi ở hiện tại' },
  { id: 'majorTrainingAlignment', label: 'Khớp ngành (aligned / outside — tự tính khi chấm)' },
  { id: 'region', label: 'Vùng / tỉnh (region)' },
  { id: 'province', label: 'Tỉnh (province)' },
  { id: 'address', label: 'Địa chỉ (address)' },
  { id: 'hanoiArea', label: 'Quận / huyện (hanoiArea)' },
  { id: 'highSchool', label: 'Trường học (highSchool)' },
  { id: 'highSchoolName', label: 'Trường THPT (alias highSchoolName)' },
  { id: 'gradeClass', label: 'Lớp hiện đang học (gradeClass)' },
  { id: 'schoolType', label: 'Loại trường (nhãn gốc)' },
  { id: 'schoolTypeKey', label: 'Loại trường (mã chuẩn hoá — tự tính khi chấm)' },
  { id: 'financialStatus', label: 'Tài chính' },
  { id: 'academicLevel', label: 'Học lực' },
  { id: 'studyIntention', label: 'Hình thức học quan tâm (studyIntention)' },
  { id: 'pipelineStatus', label: 'Pipeline (funnel)' },
  { id: 'status', label: 'CRM / Kanban' },
  { id: 'assignedTo', label: 'Tư vấn viên phụ trách (UID — assignedTo)' },
  { id: 'calculatedScore', label: 'Điểm (đã lưu)' },
  { id: 'priorityTag', label: 'Nhãn (đã lưu)' },
  { id: 'aspirations', label: 'Mong muốn / nguyện vọng (aspirations)' },
  { id: 'profileNote1', label: 'Ghi chú 1 (profileNote1)' },
  { id: 'profileNote2', label: 'Ghi chú 2 (profileNote2)' },
  { id: 'otherAttentionNotes', label: 'Nội dung lưu ý khác (otherAttentionNotes)' },
  { id: 'description', label: 'Mô tả tổng hợp legacy (description)' },
  { id: 'hobbies', label: 'Sở thích' },
  { id: 'fieldTripNotes', label: 'Ghi chú đi trường' },
  { id: 'leadSource', label: 'Nguồn tiếp nhận (leadSource)' },
  { id: 'source', label: 'Nguồn (source — trùng leadSource khi chấm)' },
  { id: 'counselorNote', label: 'Ghi chú TV (tổng hợp)', extra: true },
]
