/** Các trường có thể gửi cho LLM (id = path trên Lead hoặc key trong fieldExtras). */
export const AI_LEAD_FIELD_OPTIONS: { id: string; label: string; extra?: boolean }[] = [
  { id: 'fullName', label: 'Họ tên' },
  { id: 'phone', label: 'SĐT' },
  { id: 'email', label: 'Email' },
  { id: 'parentPhone', label: 'SĐT phụ huynh' },
  { id: 'majorInterest', label: 'Ngành quan tâm' },
  { id: 'majorTrainingAlignment', label: 'Khớp ngành (aligned / outside — tự tính khi chấm)' },
  { id: 'region', label: 'Vùng / tỉnh (region)' },
  { id: 'province', label: 'Tỉnh (province)' },
  { id: 'hanoiArea', label: 'Quận / huyện Hà Nội' },
  { id: 'highSchoolName', label: 'Trường THPT' },
  { id: 'schoolType', label: 'Loại trường (nhãn gốc)' },
  { id: 'schoolTypeKey', label: 'Loại trường (mã chuẩn hoá — tự tính khi chấm)' },
  { id: 'financialStatus', label: 'Tài chính' },
  { id: 'academicLevel', label: 'Học lực' },
  { id: 'studyIntention', label: 'Dự định (hình thức đào tạo)' },
  { id: 'pipelineStatus', label: 'Pipeline (funnel)' },
  { id: 'status', label: 'CRM / Kanban' },
  { id: 'calculatedScore', label: 'Điểm (đã lưu)' },
  { id: 'priorityTag', label: 'Nhãn (đã lưu)' },
  { id: 'aspirations', label: 'Nguyện vọng' },
  { id: 'hobbies', label: 'Sở thích' },
  { id: 'fieldTripNotes', label: 'Ghi chú đi trường' },
  { id: 'leadSource', label: 'Nguồn tiếp nhận' },
  { id: 'counselorNote', label: 'Ghi chú TV (tổng hợp)', extra: true },
]
